name: xcube_geodb
channels:
  - conda-forge

dependencies:
  - python >=3.6
  - pip
  - geopandas
  - matplotlib-base
  - psycopg2
  - requests
  - ipyleaflet
  - python-fastjsonschema
  - python-dotenv
  - pip:
    - postgis
    - requests_mock
    - testing.postgresql