name: xcube_geodb
channels:
  - conda-forge

dependencies:
  # Python
  - python >=3.6
  # Required
  - pip
  - geopandas
  - matplotlib-base
  - descartes
  - psycopg2
  - requests
  - ipyleaflet
  - python-fastjsonschema
  - python-dotenv
  - requests-mock

  # Exploring
  - jupyterlab
