name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python < 3.10 #  Pinning version lower than 3.10 as the used sphinx version does not work well with version 3.10
  - sphinx==4.0.2
  - nbsphinx==0.8.6
  - jinja2>=3.0.1
  - recommonmark
  - nbconvert
  - pandoc
  - pip
  - ipython
  - pip:
      - sphinx_rtd_theme
      - sphinxcontrib.redoc
